//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weather.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 101010100,北京,北京市,北京市
        ///101010200,海淀,北京市,北京市
        ///101010300,朝阳,北京市,北京市
        ///101010400,顺义,北京市,北京市
        ///101010500,怀柔,北京市,北京市
        ///101010600,通州,北京市,北京市
        ///101010700,昌平,北京市,北京市
        ///101010800,延庆,北京市,北京市
        ///101010900,丰台,北京市,北京市
        ///101011000,石景山,北京市,北京市
        ///101011100,大兴,北京市,北京市
        ///101011200,房山,北京市,北京市
        ///101011300,密云,北京市,北京市
        ///101011400,门头沟,北京市,北京市
        ///101011500,平谷,北京市,北京市
        ///101011600,东城,北京市,北京市
        ///101011700,西城,北京市,北京市
        ///101020100,上海,上海市,上海市
        ///101020200,闵行,上海市,上海市
        ///101020300,宝山,上海市,上海市
        ///101020400,黄浦,上海市,上海市
        ///101020500,嘉定,上海市,上海市
        ///101020600,浦东新区,上海市,上海市
        ///10 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CityKeys {
            get {
                return ResourceManager.GetString("CityKeys", resourceCulture);
            }
        }
    }
}
