//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpSxwnl {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpSxwnl.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version = &quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;SharpSxwnl&gt;
        ///&lt;SxwnlData&gt;
        ///    &lt;Data Id=&quot;JWdata_JWv&quot; Name=&quot;各地经纬度表&quot; Note=&quot;请参阅经纬数据压缩说明&quot;&gt;
        ///北京市 dshN天安门 dthS北京 dshe通州区 eDhD昌平区 e8hc顺义区 eJhc怀柔区 dihK大兴区 e8i7平谷区 eMho密云县 eSgw延庆县
        ///河北省 c3fU石家庄 c2fn藁城市 btgD辛集市 c2g2晋州市 cKfe新乐市 c5fI鹿泉市 cFfC平山县 c2f8井陉县 brfd栾城县 c8fY正定县 cQfX行唐县 cIfM灵寿县 bafb高邑县 bjfk赵县 befN赞皇县 cBgC深泽县 cBfw无极县 bjfV元氏县 dbjB唐山 doj7丰润区 dYj7丰南区 eBiv遵化市 dyjg迁安市 e9jJ迁西县 dVjf滦南县 drii玉田县 dHjS唐海县 dPjt乐亭县 dijj滦县 duka秦皇岛 dgkA昌黎县 drjq卢龙县 drkE抚宁县 eJk4青龙满族自治县 aafS [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SharpSxwnl {
            get {
                return ResourceManager.GetString("SharpSxwnl", resourceCulture);
            }
        }
    }
}
